BUG: line 156: paintIcon
NullPointerException: Cannot invoke "java.awt.Point.getX()" because "this.imageCorner" is null. Tried by putting constant in it, but then it throws an error at the 1st variable (this) as that is an observer